service: fake-store-api

package:
  patterns:
    - '!tmp/**'

provider: 
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs18.x
  environment: ${file(resources/env.yml):environment}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-west-2:*:table/fakeStoreTable
            - arn:aws:dynamodb:us-west-2:*:table/fakeStoreTable/index/*
        - Effect: Allow
          Action:
            - es:ESHttpPost
          Resource:
            - arn:aws:es:us-west-2:800521654091:domain/fake-store-domain/*
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListObject
          Resource:
            - arn:aws:s3:::fake-store-media/*

plugins: 
  - serverless-offline

functions:
  - ${file(resources/functions.yml)}

resources:
  - ${file(resources/dynamo.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/opensearch.yml)}