Resources:
  FakeStoreDomain:
    Type: 'AWS::OpenSearchService::Domain'
    Properties:
      DomainName: fake-store-domain
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t2.micro.search
        InstanceCount: 1
      EncryptionAtRestOptions: 
          Enabled: true
      NodeToNodeEncryptionOptions:
          Enabled: true
      DomainEndpointOptions:
          EnforceHTTPS: true
      EBSOptions:
        EBSEnabled: true
        Iops: 1500
        Throughput: 20
        VolumeType: gp3
        VolumeSize: 1